### ISSUE TITLE
Add different modes to quickstore

### ISSUE THREAD

**Issue by tgrosinger** [anstosa/tw5-docker#5]
Currently there is a checkbox to toggle appending vs creating a new note. I would like to extend this to instead have tabs along the top (or something like that) which add different "modes", each of which may request different fields and take different action in TiddlyWiki

Example Modes:

* **Create** - same as the default action now
* **Append** - same behavior as what exists now when "append" is checked
* **Inbox** - Accepts only a single text string which is appended to a Tiddler called "Inbox", prefaced with `[ ] ` to create or add to a [tw5-checklist](https://github.com/tgrosinger/tw5-checklist/)
    * I realize this one is a little specific to my use-case. Maybe there is a way to make it more generic without sacrificing ease-of-use?

**Comment by anstosa** [comment]
Yeah I like this idea. Would be easy enough to add optional configuration in a tiddler.

**Comment by tgrosinger** [comment]
> Would be easy enough to add optional configuration in a tiddler.

I am not sure I follow what you mean. Configuration in the tiddler itself? Not in the docker container?

**Comment by anstosa** [comment]
Like have some reserved name like `$:/plugins/anstosa/tw5-docker/config` that would have some structured data in it to set a target default tiddler to write to and an optional append prefix

**Comment by anstosa** [comment]
Could even configure it through the QuickStore UI and just save the settings to that tiddler

**Comment by tgrosinger** [comment]
Hmm, that sounds interesting. I can get started on the JS part of this, but I am going to need some UI help with it. The existing QuickStore UI was the limit of my capabilities and even that was mostly copy and pasting.

**Comment by anstosa** [comment]
Yeah I'll take a pass at it and push a branch.

**Comment by anstosa** [comment]
Okay, I think I got it working! Check out the branch `configurable-quickpost`
